config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :create, :show, :update, :destroy] do
    resources :doses, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :delete_all
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :image, ImageUploader

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :cocktail, uniqueness: {scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :select_cocktail, only: [:show, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :show
    end
  end

  def update
    @cocktail.update(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :show
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to coctails_path
  end
  
  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :image)
  end

  def select_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [:create, :destroy]

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      redirect_to cocktail_path(@cocktail)
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:amount, :description, :cocktail_id, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <div class = "form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class = "form-group">
    <%= f.input :image %>
    <%= f.input :image_cache, as: :hidden %>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/cocktails/index.html.erb
<%= render 'partials/banner' %>
<div class="wrapper">
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card">
          <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.image, height: 300, width: 400, crop: :fill %>');">
            
            <div class="card-description">
              <h2><%= cocktail.name %></h2>
              <p>Contains: <% cocktail.ingredients.first(3).each do |ingredient| %>
                <%= ingredient.name %>, 
                <% end %>
              </p>
           </div>
        <%= link_to cocktail_path(cocktail), class: "card-link" do %>
        <% end %> 
        </div>
        <div class= "card-footer">
           <%= link_to "Delete", cocktail_path(cocktail), method: :delete, data: {confirm: " Are you sure?"}, class: "delete-link" %> 
        </div>
      </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner small" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path @cocktail.image, height: 300, width: 400, crop: :fill %>');">
  <div class="banner-content">
    <h1><%= @cocktail.name %></h1>
  </div>
</div>
<div class="wrapper">
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <button type="button" class="btn btn-primary btn-sm cocktails-btn" data-toggle="modal" data-target="#myModal2">
      Edit Cocktail
       </button>
       <br>
      <button type="button" class="btn btn-primary btn-sm cocktails-btn" data-toggle="modal" data-target="#myModal3">
          Add Ingredients
       </button>
    </div>
    <div class="col-xs-12 col-sm-6">
        <h4>Recipe</h4>
        <ul class= list-unstyled>
          <% @cocktail.doses.each do |dose| %>
          <li>
            <p> <strong> <%= dose.ingredient.name %> </strong> - 
              <em><%= dose.amount  %><%= dose.description %></em>            
            <%= link_to cocktail_dose_path(@cocktail, dose), method: :delete, hidden: true do %> 
              <i class="fas fa-trash" id= "delete-link-<%=dose.id%>"></i>
            <% end %>
              <span data-id="<%=dose.id%>" class="btn btn-primary sweet-alert-d"><i class="fas fa-trash"></i></span> 
            </p>
          </li>
          <% end %>
        </ul>  
    </div>
  </div>

</div>
</div>



<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Cocktail</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', cocktail: @cocktail %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a new item in the <%= @cocktail.name.capitalize %> recipe</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@cocktail, Dose.new] do |f| %>
          <div class = "form-group">
            <%= f.association :ingredient, collection: Ingredient.order(:name), prompt: "Choose an Ingredient", class: 'form-control' %>
          </div>
          <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                  <%= f.input :amount, class: "form-control" %>
              </div>
            </div>
            <div class="col-xs-6">
              <div class = "form-group">
                <%= f.input :description, class: 'form-control' %>
              </div>
            </div>
          </div>
          <%= f.submit class: "btn btn-primary"%>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700" rel="stylesheet">
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <%= yield %>
    <%= render 'partials/footer' %>

    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->

  </body>
</html>

app/views/partials/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://www.fancyflutes.co.uk/wp-content/uploads/2016/03/banner-cocktail.jpg');">
  <div class="banner-content">
    <h1>Tails Cocktails</h1>
    <p ><span id="tagline"></span></p>
  </div>
</div>

app/views/partials/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Get the best cocktails <i class="fa fa-heart"></i> at Tails Cocktails
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to cocktails_path do %>
    <%= image_tag 'logo.png', class: 'navbar-wagon-brand' %>
    <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#myModal">
      Add New Cocktail
    </a>
    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/mjaidi" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Cocktail</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', cocktail: Cocktail.new %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>